### ISSUE TITLE
booky organization

### ISSUE THREAD

**Issue by nthiebes** [booky/firefox-plugin#2]
Hi @Nargonath,

my name is Nico and I'm the owner of [booky.io](https://booky.io). I'd like to create an organization here on GitHub for our ongoing rewrite of the project and saw that you already have one called `booky`. Any chance to move the firefox-plugin repo to your personal account and remove the booky organization or do you still have plans with it? I would be super grateful if you "free" the name :).

Kind regards,
Nico

**Comment by Nargonath** [comment]
Hi @nthiebes!

You are the second person this week asking for the ownership of this organization. 😄
The thing is that I always plan on developing this project it is just that other projects have a higher priority right now for me. 

I had a tough time finding a name I liked for my project so I'm a bit hesitant to give it over to be honest. Could you tell me a bit more about your rewrite? Is it a pure rewrite or are you changing features as well? Perhaps if your project matches my need I won't have to develop it myself.

**Comment by nthiebes** [comment]
Hey, thanks for your answer! Don't worry, the name of the organization here is not too important, it would just be convenient for us to also have an organization called `booky` and add all our repos here. If it stays occupied I'll just pick another name.

The rewrite will already add some new features. It also enables us to add new features in the future. One of the main ones will be bookmark synchronization with the browsers, similar to what you planned for this project. We already have a chrome plugin and will also add an edge/firefox and opera plugin (it's a similar codebase anyways as you probably know). The synchronization feature will most likely only be available to some sort of payed membership. Right now booky.io is still free and a private project. We're keeping it open if we want to add a payed membership in the future but everything existing will stay free.
We're actively working on the rewrite right now but it will still take some time and first be released as a beta. The existing plugin also has to be updated before we create new ones. If you're interested we could have a chat about a cooperation or similar. What you would like to do here sounds really similar and you choose the same name as well 😄.

You can reach me best via email: hello@booky.io

**Comment by Nargonath** [comment]
Thanks for your detailed answer. Sounds great indeed. I'd be happy to discuss about a cooperation or similar. I want to develop it because that's something I'm in need personally. I'll shoot you a mail soon.
